apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: "cluster2-instance"
      localASN: 65002
      peers:
        - name: "cluster1-peer"
          peerASN: 65001
          peerAddress: 192.168.2.3
          peerConfigRef:
            name: cilium-peer
