apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cluster2-bgp-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: instance-65002
    localASN: 65002
    peers:
    - name: peer-65001
      peerASN: 65001
      peerAddress: 
      peerConfigRef:
        name: cilium-peer
