apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cluster2-bgp-config
spec:
  virtualRouters:
  - localASN: 65002
    serviceSelector:
      matchExpressions:
      - {key: some-key, operator: Exists}  # <-- optional, you can delete if no filtering
    neighbors:
    - peerAddress: 192.168.2.3/32
      peerASN: 65001
    exportPodCIDR: true

