apiVersion: v1
kind: Service
metadata:
  name: test-lb-service
  labels:
    pool: cluster2-pool
    app: test-app
    advertise: bgp
spec:
  selector:
    app: test-app
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
