kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "2001:db8:2::/64"       # Cluster2 Pod CIDR (IPv6)
  serviceSubnet: "2001:db8:2:fee::/112"  # Cluster2 Service CIDR (IPv6)
nodes:
  - role: control-plane
  - role: worker
  - role: worker
