kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "2001:db8:2::/64"
  serviceSubnet: "2001:db8:2:fee::/112"
  ipFamily: ipv6
nodes:
  - role: control-plane
  - role: worker
  - role: worker
