apiVersion: apps/v1
kind: Deployment
metadata:
  name: dualstack-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dualstack-test
  template:
    metadata:
      labels:
        app: dualstack-test
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dualstack-lb
  labels:
    app: dualstack-test
    advertise: bgp
    pool: cluster2-pool
spec:
  selector:
    app: dualstack-test
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
