apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: cluster2-peering
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
  - localASN: 65002
    exportPodCIDR: true
    neighbors:
    - peerAddress: "192.168.2.3/32"
      peerASN: 65001
