version: "3.7"

services:
  frr2:
    image: frrouting/frr:v8.5.2
    container_name: frr2
    network_mode: "host"
    privileged: true
    volumes:
      - ./routers/frr2.conf:/etc/frr/frr.conf
      - /etc/iproute2:/etc/iproute2      # Optional
    environment:
      - FRR_ENABLE=bgpd
      - FRR_LOG_STDOUT=1
    restart: unless-stopped

