services:
  frr2:
    image: brunodzogovic/frr:10.3
    container_name: frr2
    network_mode: "host"
    privileged: true
    user: "0:0"
    volumes:
      - ./routers/frr2.conf:/etc/frr/frr.conf 
      - ./routers/daemons:/etc/frr/daemons
    environment:
      - FRR_ENABLE=bgpd
      - FRR_LOG_STDOUT=1
    restart: unless-stopped

