version: "3.7"

services:
  frr1:
    image: brunodzogovic/frr:10.3
    container_name: frr1
    network_mode: "host"
    privileged: true
    user: "0:0"
    volumes:
      - ./routers/frr1.conf:/etc/frr/frr.conf
      - ./routers/daemons:/etc/frr/daemons
    environment:
      - FRR_ENABLE=bgpd
      - FRR_LOG_STDOUT=1
    restart: unless-stopped

