apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cluster1-bgp-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
  - name: instance-65001
    localASN: 65001
    peers:
    - name: peer-v4
      peerASN: 65001
      peerAddress: 192.168.2.5
      peerConfigRef:
        name: cilium-peer
