apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: srv6-cluster-bgp-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k3d-srv6-cluster-server-0
  bgpInstances:
  - name: instance-65001
    localASN: 65001 
    peers:
    - name: peer-v4
      peerASN: 65001
      peerAddress: 192.168.2.5
      peerConfigRef:
        name: cilium-peer
