kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true       # We'll install Cilium manually&#8203;:contentReference[oaicite:13]{index=13}
  podSubnet: "2001:db8:1::/64"  # IPv6 Pod CIDR for cluster1 (unique)&#8203;:contentReference[oaicite:14]{index=14}
  serviceSubnet: "2001:db8:1:fee::/112"  # IPv6 Service CIDR (non-overlapping)

